In [10]:



import numpy as np
from data_loaders.humanml.scripts.motion_process import recover_from_ric
from model.rotation2xyz import Rotation2xyz
import torch
def ric2pos(sample):
    rot2xyz = Rotation2xyz(device='cpu', dataset='humanml')
    n_joints = 22 if sample.shape[1] == 263 else 21
    rot2xyz_pose_rep = 'xyz' 
    rot2xyz_mask = None 
    
    sample = recover_from_ric(sample, n_joints)
    sample = rot2xyz(x=sample, mask=rot2xyz_mask, pose_rep=rot2xyz_pose_rep, glob=True, translation=True,
                            jointstype='smpl', vertstrans=True, betas=None, beta=0, glob_rot=None,
                            get_rotations_back=False)
    return sample

id = 0


joints = np.load(f'/home/yhc/momask-codes/dataset/HumanML3D/new_joints/{id:06d}.npy')
joints_vecs = np.load(f'/home/yhc/momask-codes/dataset/HumanML3D/new_joint_vecs/{id:06d}.npy')
mean = np.load(f'/home/yhc/momask-codes/dataset/HumanML3D/Mean.npy')
std = np.load(f'/home/yhc/momask-codes/dataset/HumanML3D/Std.npy')
print(f"joints_vecs.shape: {joints_vecs.shape}")
print(f"joints.shape: {joints.shape}")
print(f"mean.shape: {mean.shape}")
print(f"std.shape: {std.shape}")
# joints_vecs_inv = joints_vecs * std[None,...] + mean[None,...]

joints_vecs_inv_recovered = ric2pos(torch.from_numpy(joints_vecs))
time_step = 0
joint_idx = [i for i in range(10)]
print(joints[time_step][joint_idx])
print(joints_vecs_inv_recovered[time_step][joint_idx])



joints_vecs.shape: (116, 263)
joints.shape: (116, 22, 3)
mean.shape: (263,)
std.shape: (263,)
[[ 0.          0.94151205  0.        ]
 [ 0.06232133  0.86118996 -0.01699019]
 [-0.05533443  0.84660774 -0.00237302]
 [-0.00556196  1.0656054  -0.04336009]
 [ 0.15537223  0.47988468 -0.04677429]
 [-0.11954129  0.46223748 -0.02196455]
 [ 0.00668192  1.2051041  -0.01346632]
 [ 0.14500111  0.04888482 -0.08038796]
 [-0.09412326  0.04250382 -0.08791802]
 [ 0.004126    1.2616646  -0.00424177]]
tensor([[ 0.0000,  0.9415,  0.0000],
        [ 0.0623,  0.8612, -0.0170],
        [-0.0553,  0.8466, -0.0024],
        [-0.0056,  1.0656, -0.0434],
        [ 0.1554,  0.4799, -0.0468],
        [-0.1195,  0.4622, -0.0220],
        [ 0.0067,  1.2051, -0.0135],
        [ 0.1450,  0.0489, -0.0804],
        [-0.0941,  0.0425, -0.0879],
        [ 0.0041,  1.2617, -0.0042]])


In [ ]:
data = np.load("/home/yhc/OmniControl/dataset/t2m_mean.npy")
print(data.shape)